# Descriptive statistics

There are a myriad sources (books, websites, videos) explaining the concepts of [descriptive statistics](https://en.wikipedia.org/wiki/Descriptive_statistics). 
We do not need to reiterate everything here. You can go through these sources to get started:

- [R for non-programmers](https://bookdown.org/daniel_dauber_io/r4np_book/descriptive-statistics.html)
- [Science direct](https://www.sciencedirect.com/topics/social-sciences/descriptive-statistics)

The goal is to describe data in a meaningful and honest way. 
We **summarize** data to make them **more easily digestable** for us humans to answer questions like 

- Where are the data points **located**? 
  These questions are answered (at least attempted) by the location measures such as 
  [mean](https://en.wikipedia.org/wiki/Mean), [median](https://en.wikipedia.org/wiki/Median), and [mode](https://en.wikipedia.org/wiki/Mode_(statistics)).
- How widely are they spread? How much do they **vary**?
  These questions are answered by the dispersion measures such as [variance](https://en.wikipedia.org/wiki/Variance), 
  [standard deviation](https://en.wikipedia.org/wiki/Standard_deviation) (root of the variance), 
  [interquantile range](https://en.wikipedia.org/wiki/Interquartile_range#:~:text=The%20IQR%20of%20a%20set,a%20median%20calculated%20as%20follows.&text=The%20second%20quartile%20Q2%20is%20the%20same%20as%20the%20ordinary%20median.) 
  or just the [range](https://en.wikipedia.org/wiki/Range_(statistics)); or even [Gini's mean difference](https://www.dss.uniroma1.it/RePec/mtn/articoli/2003-2-8.pdf).
- Are there any **outliers** (rare data points that are far away from the rest [@westfall2020, p. 405].) and why?
  This is a bit more complicated.

## Example: Descriptive statistics in health sciences {#example_study1_physio}

These are birds-eye views on the data. Let's look at a paper which was recently published in the 
[Journal of Physiotherapy](https://www.sciencedirect.com/journal/journal-of-physiotherapy) in order to get a running start:

[Patients with worse disability respond best to cognitive functional therapy for chronic low back pain: a pre-planned secondary analysis of a randomised trial](https://www.sciencedirect.com/science/article/pii/S183695532400081X?via%3Dihub)

(This should be open access.)

The research question was "Do five baseline moderators identify patients with chronic low back pain who respond best to cognitive 
functional therapy (CFT) when compared with usual care?".

In **Table 2** of the paper, the authors present the baseline characteristics of the patients stratified by the treatment group (ususal care vs CFT).
We find absolute numbers, percentages, means, and standard deviations for the continuous variables, medians, and interquartile ranges for the ordinal variables.
This should give an idea of the sample. In the population paradigm of statistics, we draw a [sample](https://en.wikipedia.org/wiki/Sampling_(statistics)) from 
the [population](https://en.wikipedia.org/wiki/Statistical_population) of interest and try to make inferences about the population. We want to learn
more about the population respectively that data generating process (DGP) producing the data [@westfall2020, pp. 6-8]. How did the data come about?
Note that this **sample varies everytime we draw from the population**. 
We can either imagine an infinitely large population or a finite one (e.g. population of Switzerland).

Often, variables in a study are (approximately) normally distributed. 
We can then efficiently summarize the variable with its mean and standard deviation (location and scale parameter) as is done 
in the paper for *Age* in years for instance. We do not want to present p-values in such an overview table since we merely *describe* data instead of
making inferences about the population or the DGP.
It is by no means given that *age* has to be normally distributed in our sample. We could easily have a sample with many young people and few elderly ones.
This would result in a (positively) [*skewed*](https://en.wikipedia.org/wiki/Skewness) distribution. Having many elderly people and few young ones would 
result in a negatively skewed distribution of course.

## Univarate vs. bivariate statisics 
One can distinguish between [univariate](https://en.wikipedia.org/wiki/Univariate_analysis) and [bivariate](https://en.wikipedia.org/wiki/Bivariate_analysis) statistics.
In univariate statistics, we look at one variable at a time, for instance *Age* in the example above, 
where we could draw a [boxplot](https://en.wikipedia.org/wiki/Box_plot) or a [histogram](https://en.wikipedia.org/wiki/Histogram). 
Table 2 in the paper is a good example of univariate statistics. We are not so much interested in the relationship between variables.

In bivariate statistics, we look at two variables *simultaneously*. 
An example could a [scatter plot](https://en.wikipedia.org/wiki/Scatter_plot) of *Age* and *Cognitive flexibility*, 
where we would possible find a falling relationship.

[Multivariate statistics](https://en.wikipedia.org/wiki/Multivariate_statistics) is the next step, where we look at more than two variables at the same time.

## Exercises

### Exercise 1 - Recreate table with fake data
 - Create fake data for the study mentioned [above](#example_study1_physio) in R.
 - Recreate Table 2 of the paper mentioned [above](#example_study1_physio) with fake data in R (using GPT, the R package *gtsummary* and other useful packages). 
   This is rather helpful later on in your master thesis.
 - Try to export the table to Excel and Word.

### Exercsie 2 - Outliers and estimates
Let's assume we know that the *Cognitive flexibility* is normally distributed with a mean of 60 and a standard deviation of 7.4 (Table 1): $CognFlex \sim N(60,7.4)$.

- Draw a sample of 165 persons from this distribution and calculate the mean and standard deviation of the sample. 
  How good is the estimate of the true (and in this case: known) mean and standard deviation?
- Let's replace some of the data points with outliers. Change the score of 5 persons with to impossible CognFlex score of 100. 
  Calculate the mean and standard deviation of the sample. How do the estimates change?
- When we try to estimate the location of our *Cognitive flexibility* distribution with the median, 
  how many outliers of what magnitude are necessary to disturb the estimate by 5 points? 

### Exercise 3 - Recreating data in Table 2 {#exercise1_descriptive_stats}
We assume that *age* in both groups is normally distributed with a mean of 48 (47) years 
and a standard deviation of 16 (15) years: 

$Age_{UsualCare} \sim Normal(\mu = 48, \sigma = 16)$ and 

$Age_{CFT} \sim Normal(\mu = 47,\sigma = 15)$.

- Under these assumptions, what is the probability, that we would see a person of age 60 or older in a new sample (in either group)?
- What is the probability, that we would see a person of age 18 or younger in a new sample?
- Give a 99% interval for the age in CFT, 
  where we would expect a new person drawn from the same population.

Let's assume *Sex* is binomially distributed with a probability of $p = 0.59$ for both groups.

- What is the probability, that we would see a woman as the next recruited person in the *Usual care* group?
- What is the probability, that we would see no man in a sample of 10 persons in the *CFT* group?
- Sometimes you want balanced samples. How many patients would we need to recruit to get at least 45 women with a probability of at least 90%. 
  (We could solve this with simulation.) 

## Solutions
Solutions for this chapter can be found [here](https://github.com/jdegenfellner/Script_QM1_ZHAW/tree/main/Solutions_to_Exercises/3_Descriptive_statistics).